/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import homepage.HomePage;
import java.awt.Color;
import java.awt.event.MouseEvent;

/**
 *
 * @author Junayed
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUp = new javax.swing.JPopupMenu();
        Settings = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admin_logo = new javax.swing.JLabel();
        dab_text = new javax.swing.JLabel();
        left_menu = new javax.swing.JPanel();
        lm_allContent = new javax.swing.JPanel();
        lm_ac_text = new javax.swing.JLabel();
        lm_addContent = new javax.swing.JPanel();
        lm_adc_text = new javax.swing.JLabel();
        lm_comments = new javax.swing.JPanel();
        lm_cmt_text = new javax.swing.JLabel();
        lm_authors = new javax.swing.JPanel();
        lm_a_text = new javax.swing.JLabel();
        lm_previewContent = new javax.swing.JPanel();
        lm_pc_text = new javax.swing.JLabel();
        lm_newAuthors = new javax.swing.JPanel();
        lm_na_text = new javax.swing.JLabel();
        Menu = new javax.swing.JTabbedPane();
        dashboard = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        all_content = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        add_content = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        preveiw_content = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        comments = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        authors = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        new_authors = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        addab_settings = new javax.swing.JPanel();
        settings_text = new javax.swing.JLabel();

        PopUp.setBackground(new java.awt.Color(0, 0, 0));

        Settings.setText("Settings");
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsActionPerformed(evt);
            }
        });
        PopUp.add(Settings);

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setText("Log out");
        Logout.setPreferredSize(new java.awt.Dimension(100, 17));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        PopUp.add(Logout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Hello, Admin");

        admin_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatar.png"))); // NOI18N
        admin_logo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        admin_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_logoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admin_logoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                admin_logoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                admin_logoMouseReleased(evt);
            }
        });

        dab_text.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        dab_text.setForeground(new java.awt.Color(204, 204, 204));
        dab_text.setText("Dashboard");
        dab_text.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dab_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dab_textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(dab_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 704, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_logo)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(admin_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dab_text))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 65));

        left_menu.setBackground(new java.awt.Color(51, 51, 51));

        lm_allContent.setBackground(new java.awt.Color(204, 204, 204));
        lm_allContent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lm_allContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lm_allContentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lm_allContentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lm_allContentMouseExited(evt);
            }
        });

        lm_ac_text.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lm_ac_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lm_ac_text.setText("All Content");

        javax.swing.GroupLayout lm_allContentLayout = new javax.swing.GroupLayout(lm_allContent);
        lm_allContent.setLayout(lm_allContentLayout);
        lm_allContentLayout.setHorizontalGroup(
            lm_allContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_ac_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lm_allContentLayout.setVerticalGroup(
            lm_allContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_ac_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        lm_addContent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lm_addContent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lm_addContentMouseMoved(evt);
            }
        });
        lm_addContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lm_addContentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lm_addContentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lm_addContentMouseExited(evt);
            }
        });

        lm_adc_text.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lm_adc_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lm_adc_text.setText("Add Content");

        javax.swing.GroupLayout lm_addContentLayout = new javax.swing.GroupLayout(lm_addContent);
        lm_addContent.setLayout(lm_addContentLayout);
        lm_addContentLayout.setHorizontalGroup(
            lm_addContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_adc_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lm_addContentLayout.setVerticalGroup(
            lm_addContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_adc_text, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        lm_comments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lm_comments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lm_commentsMouseClicked(evt);
            }
        });

        lm_cmt_text.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lm_cmt_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lm_cmt_text.setText("Comments");

        javax.swing.GroupLayout lm_commentsLayout = new javax.swing.GroupLayout(lm_comments);
        lm_comments.setLayout(lm_commentsLayout);
        lm_commentsLayout.setHorizontalGroup(
            lm_commentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_cmt_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lm_commentsLayout.setVerticalGroup(
            lm_commentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_cmt_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        lm_authors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lm_authors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lm_authorsMouseClicked(evt);
            }
        });

        lm_a_text.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lm_a_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lm_a_text.setText("Authors");

        javax.swing.GroupLayout lm_authorsLayout = new javax.swing.GroupLayout(lm_authors);
        lm_authors.setLayout(lm_authorsLayout);
        lm_authorsLayout.setHorizontalGroup(
            lm_authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_a_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lm_authorsLayout.setVerticalGroup(
            lm_authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_a_text, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        lm_previewContent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lm_previewContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lm_previewContentMouseClicked(evt);
            }
        });

        lm_pc_text.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lm_pc_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lm_pc_text.setText("Preview Content");

        javax.swing.GroupLayout lm_previewContentLayout = new javax.swing.GroupLayout(lm_previewContent);
        lm_previewContent.setLayout(lm_previewContentLayout);
        lm_previewContentLayout.setHorizontalGroup(
            lm_previewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_pc_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lm_previewContentLayout.setVerticalGroup(
            lm_previewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_pc_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        lm_newAuthors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lm_newAuthors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lm_newAuthorsMouseClicked(evt);
            }
        });

        lm_na_text.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lm_na_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lm_na_text.setText("New Authors");

        javax.swing.GroupLayout lm_newAuthorsLayout = new javax.swing.GroupLayout(lm_newAuthors);
        lm_newAuthors.setLayout(lm_newAuthorsLayout);
        lm_newAuthorsLayout.setHorizontalGroup(
            lm_newAuthorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lm_newAuthorsLayout.createSequentialGroup()
                .addComponent(lm_na_text, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        lm_newAuthorsLayout.setVerticalGroup(
            lm_newAuthorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lm_na_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout left_menuLayout = new javax.swing.GroupLayout(left_menu);
        left_menu.setLayout(left_menuLayout);
        left_menuLayout.setHorizontalGroup(
            left_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_menuLayout.createSequentialGroup()
                .addComponent(lm_newAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(left_menuLayout.createSequentialGroup()
                .addGroup(left_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lm_authors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lm_comments, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lm_previewContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lm_addContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lm_allContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        left_menuLayout.setVerticalGroup(
            left_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_menuLayout.createSequentialGroup()
                .addComponent(lm_allContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lm_addContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lm_previewContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lm_comments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lm_authors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lm_newAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 296, Short.MAX_VALUE))
        );

        getContentPane().add(left_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 190, 682));

        Menu.setBackground(new java.awt.Color(255, 255, 255));

        dashboard.setBackground(new java.awt.Color(255, 255, 255));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Dashboard");
        dashboard.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 280, 110));

        Menu.addTab("tab1", dashboard);

        all_content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("All Content");

        javax.swing.GroupLayout all_contentLayout = new javax.swing.GroupLayout(all_content);
        all_content.setLayout(all_contentLayout);
        all_contentLayout.setHorizontalGroup(
            all_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, all_contentLayout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        all_contentLayout.setVerticalGroup(
            all_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_contentLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        Menu.addTab("tab2", all_content);

        add_content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Add Content");

        javax.swing.GroupLayout add_contentLayout = new javax.swing.GroupLayout(add_content);
        add_content.setLayout(add_contentLayout);
        add_contentLayout.setHorizontalGroup(
            add_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_contentLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        add_contentLayout.setVerticalGroup(
            add_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_contentLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        Menu.addTab("tab3", add_content);

        preveiw_content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Preview Content");

        javax.swing.GroupLayout preveiw_contentLayout = new javax.swing.GroupLayout(preveiw_content);
        preveiw_content.setLayout(preveiw_contentLayout);
        preveiw_contentLayout.setHorizontalGroup(
            preveiw_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, preveiw_contentLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        preveiw_contentLayout.setVerticalGroup(
            preveiw_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preveiw_contentLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        Menu.addTab("tab4", preveiw_content);

        comments.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel15.setText("Comments");

        javax.swing.GroupLayout commentsLayout = new javax.swing.GroupLayout(comments);
        comments.setLayout(commentsLayout);
        commentsLayout.setHorizontalGroup(
            commentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commentsLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        commentsLayout.setVerticalGroup(
            commentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentsLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        Menu.addTab("tab5", comments);

        authors.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel16.setText("Authors");

        javax.swing.GroupLayout authorsLayout = new javax.swing.GroupLayout(authors);
        authors.setLayout(authorsLayout);
        authorsLayout.setHorizontalGroup(
            authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authorsLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        authorsLayout.setVerticalGroup(
            authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorsLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        Menu.addTab("tab6", authors);

        new_authors.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel17.setText("New Authors");

        javax.swing.GroupLayout new_authorsLayout = new javax.swing.GroupLayout(new_authors);
        new_authors.setLayout(new_authorsLayout);
        new_authorsLayout.setHorizontalGroup(
            new_authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_authorsLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        new_authorsLayout.setVerticalGroup(
            new_authorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_authorsLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        Menu.addTab("tab7", new_authors);

        settings_text.setText("Settings");

        javax.swing.GroupLayout addab_settingsLayout = new javax.swing.GroupLayout(addab_settings);
        addab_settings.setLayout(addab_settingsLayout);
        addab_settingsLayout.setHorizontalGroup(
            addab_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addab_settingsLayout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(settings_text)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        addab_settingsLayout.setVerticalGroup(
            addab_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addab_settingsLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(settings_text)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        Menu.addTab("tab8", addab_settings);

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 820, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showPopUp(MouseEvent e){
        PopUp.show(this, 890,90);
    }
//    
    private void admin_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_logoMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_admin_logoMouseClicked

    private void admin_logoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_logoMouseEntered
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            showPopUp(evt);
        }
    }//GEN-LAST:event_admin_logoMouseEntered

    private void admin_logoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_logoMousePressed
        // TODO add your handling code here:
         if(evt.isPopupTrigger()){
            showPopUp(evt);
        }
    }//GEN-LAST:event_admin_logoMousePressed

    private void admin_logoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_logoMouseReleased
        // TODO add your handling code here:
         if(evt.isPopupTrigger()){
            showPopUp(evt);
        }
    }//GEN-LAST:event_admin_logoMouseReleased

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomePage i = new HomePage();
        i.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(7);
    }//GEN-LAST:event_SettingsActionPerformed

    private void lm_allContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_allContentMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(1);
        lm_allContent.setBackground(Color.white);
        lm_addContent.setBackground(new Color(204,204,204));
        lm_previewContent.setBackground(new Color(204,204,204));
        lm_comments.setBackground(new Color(204,204,204));
        lm_authors.setBackground(new Color(204,204,204));
        lm_newAuthors.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lm_allContentMouseClicked

    private void dab_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dab_textMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(0);
        lm_allContent.setBackground(new Color(204,204,204));
        lm_addContent.setBackground(new Color(204,204,204));
        lm_previewContent.setBackground(new Color(204,204,204));
        lm_comments.setBackground(new Color(204,204,204));
        lm_authors.setBackground(new Color(204,204,204));
        lm_newAuthors.setBackground(new Color(204,204,204));
        
    }//GEN-LAST:event_dab_textMouseClicked

    private void lm_addContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_addContentMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(2);
        lm_allContent.setBackground(new Color(204,204,204));
        lm_addContent.setBackground(Color.white);
        lm_previewContent.setBackground(new Color(204,204,204));
        lm_comments.setBackground(new Color(204,204,204));
        lm_authors.setBackground(new Color(204,204,204));
        lm_newAuthors.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lm_addContentMouseClicked

    private void lm_previewContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_previewContentMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(3);
        lm_allContent.setBackground(new Color(204,204,204));
        lm_addContent.setBackground(new Color(204,204,204));
        lm_previewContent.setBackground(Color.white);
        lm_comments.setBackground(new Color(204,204,204));
        lm_authors.setBackground(new Color(204,204,204));
        lm_newAuthors.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lm_previewContentMouseClicked

    private void lm_commentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_commentsMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(4);
        lm_allContent.setBackground(new Color(204,204,204));
        lm_addContent.setBackground(new Color(204,204,204));
        lm_previewContent.setBackground(new Color(204,204,204));
        lm_comments.setBackground(Color.white);
        lm_authors.setBackground(new Color(204,204,204));
        lm_newAuthors.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lm_commentsMouseClicked

    private void lm_authorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_authorsMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(5);
        lm_allContent.setBackground(new Color(204,204,204));
        lm_addContent.setBackground(new Color(204,204,204));
        lm_previewContent.setBackground(new Color(204,204,204));
        lm_comments.setBackground(new Color(204,204,204));
        lm_authors.setBackground(Color.white);
        lm_newAuthors.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lm_authorsMouseClicked

    private void lm_newAuthorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_newAuthorsMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(6);
        lm_allContent.setBackground(new Color(204,204,204));
        lm_addContent.setBackground(new Color(204,204,204));
        lm_previewContent.setBackground(new Color(204,204,204));
        lm_comments.setBackground(new Color(204,204,204));
        lm_authors.setBackground(new Color(204,204,204));
        lm_newAuthors.setBackground(Color.white);
    }//GEN-LAST:event_lm_newAuthorsMouseClicked

    private void lm_allContentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_allContentMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lm_allContentMouseEntered

    private void lm_allContentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_allContentMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lm_allContentMouseExited

    private void lm_addContentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_addContentMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lm_addContentMouseEntered

    private void lm_addContentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_addContentMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lm_addContentMouseExited

    private void lm_addContentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lm_addContentMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lm_addContentMouseMoved

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        // TODO add your handling code here:
        Menu.setSelectedIndex(7);
    }//GEN-LAST:event_SettingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logout;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JPopupMenu PopUp;
    private javax.swing.JMenuItem Settings;
    private javax.swing.JPanel add_content;
    private javax.swing.JPanel addab_settings;
    private javax.swing.JLabel admin_logo;
    private javax.swing.JPanel all_content;
    private javax.swing.JPanel authors;
    private javax.swing.JPanel comments;
    private javax.swing.JLabel dab_text;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left_menu;
    private javax.swing.JLabel lm_a_text;
    private javax.swing.JLabel lm_ac_text;
    private javax.swing.JLabel lm_adc_text;
    private javax.swing.JPanel lm_addContent;
    private javax.swing.JPanel lm_allContent;
    private javax.swing.JPanel lm_authors;
    private javax.swing.JLabel lm_cmt_text;
    private javax.swing.JPanel lm_comments;
    private javax.swing.JLabel lm_na_text;
    private javax.swing.JPanel lm_newAuthors;
    private javax.swing.JLabel lm_pc_text;
    private javax.swing.JPanel lm_previewContent;
    private javax.swing.JPanel new_authors;
    private javax.swing.JPanel preveiw_content;
    private javax.swing.JLabel settings_text;
    // End of variables declaration//GEN-END:variables
}
